spring:
  datasource:
     url: jdbc:postgresql://mydbinstance.cwblf8lajcuh.us-west-1.rds.amazonaws.com/Fiskkit_Instant_Email
     username: root
     password: SLvX92gBJqK7ykX4yJtQvV
 
  jpa:
     hibernate:
       ddl-auto: create-drop
     show-sql: true 
logging:
  level:
    root: TRACE

flyway:
  enabled: true 
  locations: ""
  baselineOnMigrate: true

chargebee:
  applicationEnvironment: fiskkit-test
  applicationSecret: test_raQe0j3cucuVve0wl3O4bckERSrLrHkRxl

server:
  compression: 
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

fiskkit:
  tweetMessage: Read the new fisk -- $link&random=$random $twitterScreenname